src/Defra.PTS.Web.UI/Controllers/TravelDocumentController.cs
using Defra.PTS.Web.Application.Constants;
using Defra.PTS.Web.Application.DTOs.Services;
using Defra.PTS.Web.Application.Features.DynamicsCrm.Commands;
using Defra.PTS.Web.Application.Features.TravelDocument.Queries;
using Defra.PTS.Web.Application.Features.Users.Commands;
using Defra.PTS.Web.Application.Features.Users.Queries;

using Defra.PTS.Web.Application.Services.Interfaces;
using Defra.PTS.Web.Domain.Models;
using Defra.PTS.Web.Domain.ViewModels;
using Defra.PTS.Web.UI.Constants;
using Defra.PTS.Web.UI.Extensions;
using MediatR;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Diagnostics.CodeAnalysis;
using System.Security.Claims;
using Microsoft.Extensions.Localization;
using Microsoft.Azure.Management.BatchAI.Fluent.Models;
using Defra.PTS.Web.UI.Helpers;
using Defra.PTS.Web.Domain.Enums;

namespace Defra.PTS.Web.UI.Controllers;

[Authorize]
public partial class TravelDocumentController : BaseTravelDocumentController
{

    private readonly IMediator _mediator;
    private readonly ILogger<TravelDocumentController> _logger;
    private readonly PtsSettings _ptsSettings;
    private readonly ISelectListLocaliser _selectListLocaliser;
    private readonly IStringLocalizer<ISharedResource> _localizer;

    public TravelDocumentController(
          IValidationService validationService,
          IMediator mediator,
          ILogger<TravelDocumentController> logger,
          IOptions<PtsSettings> ptsSettings,
          ISelectListLocaliser breedHelper,
          IStringLocalizer<ISharedResource> localizer
          )
    {
        ArgumentNullException.ThrowIfNull(validationService);
        ArgumentNullException.ThrowIfNull(mediator);
        ArgumentNullException.ThrowIfNull(logger);
        ArgumentNullException.ThrowIfNull(ptsSettings);

        _mediator = mediator;
        _logger = logger;
        _selectListLocaliser = breedHelper;
        _localizer = localizer;
        _ptsSettings = ptsSettings.Value;
   
    }

    [ExcludeFromCodeCoverage]
    [HttpGet]
    public async Task<IActionResult> Index()
    {
        try
        {
            if (HttpContext != null && HttpContext.Session != null)
            {
                HttpContext.Session.SetString("SessionActive", "yes");
            }

            if (HttpContext.Session.TryGetValue("ManagementLinkClicked", out byte[] managementLinkClicked) && System.Text.Encoding.UTF8.GetString(managementLinkClicked) == "true")
            {
                return RedirectToAction("CheckIdm2SignOut", "User");
            }

            if (HttpContext.Request.Cookies.TryGetValue(".AspNetCore.Culture", out string language) && language == "c=cy|uic=cy")
            {
                Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("cy");
            }

            var magicWordData = GetMagicWordFormData(true);

            if (_ptsSettings.MagicWordEnabled && magicWordData != null && !magicWordData.HasUserPassedPasswordCheck)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                SaveMagicWordFormData(new MagicWordViewModel { HasUserPassedPasswordCheck = true });

                SetBackUrl(string.Empty);

                await AddOrUpdateUser();
                await InitializeUserDetails();

                var validStatuses = new List<string>
                {
                    AppConstants.ApplicationStatus.APPROVED,
                    AppConstants.ApplicationStatus.AWAITINGVERIFICATION,
                    AppConstants.ApplicationStatus.SUSPENDED
                };

                var invalidStatuses = new List<string>
                {
                    AppConstants.ApplicationStatus.REVOKED,
                    AppConstants.ApplicationStatus.UNSUCCESSFUL
                };

                var userId = CurrentUserId();
                var response = await _mediator.Send(new GetApplicationsQueryRequest(userId, validStatuses));
                var invalidResponse = await _mediator.Send(new GetApplicationsQueryRequest(userId, invalidStatuses));

                SaveIsUserSuspendedFormData(response.Applications.Any(x => x.Status == "Suspended"));

                // Pass a flag to the view indicating whether invalid documents exist
                ViewBag.HasInvalidDocuments = invalidResponse.Applications.Count > 0;

                return View(response.Applications);
            }
        }
        catch (Exception ex)
        {
            return HandleException(ex);
        }
    }

    [ExcludeFromCodeCoverage]
    [HttpGet]
    public async Task<IActionResult> InvalidDocuments()
    {
   
        try 
        {
            SetBackUrl(WebAppConstants.Pages.TravelDocument.Index);

            await AddOrUpdateUser();
            await InitializeUserDetails();

            var statuses = new List<string>()
            {
                AppConstants.ApplicationStatus.REVOKED,
                AppConstants.ApplicationStatus.UNSUCCESSFUL
            };

            var userId = CurrentUserId();
            var response = await _mediator.Send(new GetApplicationsQueryRequest(userId, statuses));

            var sortedApplications = response.Applications // Sort by DateOfApplication or DocumentIssueDate, whichever is the latter
                .OrderByDescending(x => 
                    new[] { x.DateOfApplication, x.DocumentIssueDate }
                        .Max(d => d ?? DateTime.MinValue)
                )
                .ToList();

            return View(sortedApplications);
        }
        catch (Exception ex)
        {
            return HandleException(ex);
        }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult ApplicationDetailRecord(string id, string status)
    {
        
        HttpContext.Session.SetString("ApplicationId", id);        

        if (status == AppConstants.ApplicationStatus.APPROVED)
            return RedirectToAction(nameof(ApplicationCertificate));
        else
            return RedirectToAction(nameof(ApplicationDetails));


    }

    #region Private Methods
    [ExcludeFromCodeCoverage]
    private async Task AddOrUpdateUser()
    {
        var userInfo = GetCurrentUserInfo();

        var response = await _mediator.Send(new AddUserRequest(userInfo));
        if (response.IsSuccess)
        {
            var identity = HttpContext.User.Identities.FirstOrDefault();
            identity?.AddClaim(new Claim(WebAppConstants.IdentityKeys.PTSUserId, response.UserId.ToString()));
        }
    }

    [ExcludeFromCodeCoverage]
    private async Task<UserDetailDto> InitializeUserDetails()
    {
        // Save user
        var userInfo = GetCurrentUserInfo();

        try
        {
            await _mediator.Send(new AddAddressRequest(userInfo));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Unable to save address details, {Message}", ex.Message);
        }
        var contactId = CurrentUserContactId();
        var response = await _mediator.Send(new GetUserDetailQueryRequest(contactId));
        if (response != null && response.UserDetail != null)
        {

            HttpContext.Session.SetString("FullName", response.UserDetail?.FullName);
            return response.UserDetail;
        }

        return null;
    }


    public override HttpContext GetHttpContext()
    {
        return HttpContext;
    }

    public Guid CurrentUserContactId()
    {
        if (GetHttpContext().User.Identity.IsAuthenticated)
        {
            var contactId = GetHttpContext().User.GetLoggedInContactId();
            return contactId;
        }

        return Guid.Empty;
    }

    public User GetCurrentUserInfo()
    {
        var identity = GetHttpContext().User.Identities.FirstOrDefault();
        if (identity == null)
        {
            return new User();
        }

        var claims = identity.Claims;

        var user = new User();
        foreach (var claim in claims)
        {
            switch (claim.Type)
            {
                case "contactId":
                    user.ContactId = claim.Value;
                    break;
                case "uniqueReference":
                    user.UniqueReference = claim.Value;
                    break;
                case "firstName":
                    user.FirstName = claim.Value;
                    break;
                case "lastName":
                    user.LastName = claim.Value;
                    break;
                case "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress":
                    user.EmailAddress = claim.Value;
                    break;
                case "http://schemas.microsoft.com/ws/2008/06/identity/claims/role":
                    user.Role = claim.Value;
                    break;
                default:
                    break;
            }
        }

        return user;
    }

    #endregion Private Methods
}

src/Defra.PTS.Web.UI/Views/TravelDocument/PetAge.cshtml
@model PetAgeViewModel
@using Defra.PTS.Web.Domain.ViewModels.TravelDocument;
@using Defra.PTS.Web.Domain.Enums;
@using Defra.PTS.Web.Domain.ViewModels;
@using Defra.PTS.Web.UI.Constants;
@using Defra.PTS.Web.UI.Extensions;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.Extensions.Localization;
@inject IStringLocalizer<ISharedResource> sharedlocalizer
@inject IViewLocalizer Localizer

@{
    var fieldsetLegend = new FieldsetLegendViewModel { Label = Localizer[PetAgeViewModel.FormTitle].Value, LabelFor = "Day" };
    this.SetMetaTitle(PetAgeViewModel.FormTitle);
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        @using (Html.BeginForm("PetAge", "TravelDocument", FormMethod.Post, new { @class = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.IsCompleted)
            @Html.HiddenFor(x => x.MicrochippedDate)

            <partial name="_ErrorSummary" />

            <div class="govuk-form-group @(ViewData.ModelState.IsValid ? "" : "govuk-form-group--error")">

                <fieldset class="govuk-fieldset" aria-describedby="pet-age-hint">                    
                    <partial name="_FieldsetLegend" model=fieldsetLegend />

                    <div id="pet-age-hint" class="govuk-hint">

                        @Localizer["Your pet's date of birth should be displayed on their microchip certificate."]

                        @Localizer["Use an approximate date of birth if you are unsure."]

                    </div>

                    <div class="govuk-form-group">

                        <div id="petDOB-hint" class="govuk-hint">
                            @Localizer["For example, 27 3 2020"]
                        </div>

                        <div class="govuk-radios" data-module="govuk-radios">
                            <div class="govuk-form-group">

                                <fieldset class="govuk-fieldset" role="group" aria-describedby="petDOB-hint">
                                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl govuk-visually-hidden">Enter date of birth</legend>

                                    @Html.ValidationMessageFor(x => x.BirthDate, string.Empty, new { @class="govuk-error-message"})
                                    @Html.ValidationMessageFor(x => x.Day, string.Empty, new { @class="govuk-error-message"})
                                    @Html.ValidationMessageFor(x => x.Month, string.Empty, new { @class="govuk-error-message"})
                                    @Html.ValidationMessageFor(x => x.Year, string.Empty, new { @class="govuk-error-message"})

                                    <div class="govuk-date-input" id="BirthDate">
                                        <div class="govuk-date-input__item">
                                            <div class="govuk-form-group">
                                                <label class="govuk-label govuk-date-input__label" for="Day">
                                                    @sharedlocalizer["Day"]
                                                </label>
                                                @Html.TextBoxFor(x => x.Day, new { @class = "govuk-input govuk-date-input__input govuk-input--width-2", id = "Day", @spellcheck = "false"})
                                            </div>
                                        </div>
                                        <div class="govuk-date-input__item">
                                            <div class="govuk-form-group">
                                                <label class="govuk-label govuk-date-input__label" for="Month">
                                                    @sharedlocalizer["Month"]
                                                </label>
                                                @Html.TextBoxFor(x => x.Month, new { @class = "govuk-input govuk-date-input__input govuk-input--width-2", id = "Month", @spellcheck = "false"})
                                            </div>
                                        </div>
                                        <div class="govuk-date-input__item">
                                            <div class="govuk-form-group">
                                                <label class="govuk-label govuk-date-input__label" for="Year">
                                                    @sharedlocalizer["Year"]
                                                </label>
                                                @Html.TextBoxFor(x => x.Year, new { @class = "govuk-input govuk-date-input__input govuk-input--width-4", id = "Year", @spellcheck = "false"})
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>

                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>

            <div class="govuk-button-group">
                <button class="govuk-button" data-module="govuk-button" type="submit">
                    @sharedlocalizer["Continue"]
                </button>
            </div>
        }

    </div>
</div>

src/Defra.PTS.Web.UI/Views/TravelDocument/PetFeature.cshtml
@model PetFeatureViewModel
@using Defra.PTS.Web.Application.Extensions;
@using Defra.PTS.Web.Domain.ViewModels.TravelDocument;
@using Defra.PTS.Web.Domain.Enums;
@using Defra.PTS.Web.Domain.ViewModels;
@using Defra.PTS.Web.UI.Constants;
@using Defra.PTS.Web.UI.Extensions;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@using Microsoft.Extensions.Localization;
@inject IStringLocalizer<ISharedResource> sharedlocalizer

@{
    this.SetMetaTitle(Localizer[PetFeatureViewModel.FormTitle].Value);
}

<div class="govuk-grid-row">
    <div id="formroot" class="govuk-grid-column-two-thirds">

        @using (Html.BeginForm("PetFeature", "TravelDocument", FormMethod.Post, new { @class = "form PetFeature" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.IsCompleted)

            <partial name="_ErrorSummary" />
            
            <div class="govuk-form-group (@ViewData.ModelState.HasError("HasUniqueFeature") ? " govuk-form-group--error" : null)">
                <fieldset class="govuk-fieldset govuk-!-margin-bottom-5" aria-describedby="@(ViewData.ModelState.HasError("HasUniqueFeature") ? "OptionSelected_Error": null)">
                    <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
                        <h1 class="govuk-fieldset__heading">
                            @Localizer["Does your pet have any significant features?"]
                        </h1>
                    </legend>

                    <div id="feature-hint" class="govuk-hint">
                        <p class="govuk-body">
                            @Localizer["A significant feature is anything that can help us to identify your pet."]
                            <br />
                            @Localizer["For example, if your pet has one eye or a missing leg."]
                        </p>
                    </div>
                    @Html.ValidationMessageFor(x => x.HasUniqueFeature, string.Empty, new { @class = "govuk-error-message" })

                    <p id="OptionSelected_Error" class="govuk-error-message" gds-validation-for="HasUniqueFeature"></p>
                    <div class="govuk-radios" data-module="govuk-radios" id="HasUniqueFeature">
                        <div id="FeatureDescriptionRadios" class="govuk-form-group @(ViewData.ModelState.HasError("HasUniqueFeature") ? "govuk-form-group--error" : null)">
                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" type="radio" id="HasUniqueFeatureYes" asp-for="HasUniqueFeature" value="@YesNoOptions.Yes" aria-controls="conditional-feature" aria-expanded="false">
                                <label class="govuk-label govuk-radios__label" for="HasUniqueFeatureYes">
                                    @sharedlocalizer["Yes"]
                                </label>
                            </div>

                            <div class="govuk-radios__conditional govuk-radios__conditional--hidden" id="conditional-feature">
                                <div class="govuk-form-group @(ViewData.ModelState.HasError("FeatureDescription") ? "govuk-form-group--error" : null)">
                                    <div class="govuk-form-group">
                                        <label class="govuk-label govuk-label--s" for="FeatureDescription">
                                            @Localizer["Briefly describe your pet's significant feature"]
                                        </label>
                                        @Html.ValidationMessageFor(x => x.FeatureDescription, string.Empty, new { @class = "govuk-error-message" })
                                        <textarea class="govuk-textarea" id="FeatureDescription" rows="5" asp-for="FeatureDescription" spellcheck="false"></textarea>
                                    </div>
                                </div>
                            </div>

                            <div class="govuk-radios__item">
                                <input class="govuk-radios__input" type="radio" id="HasUniqueFeatureNo" asp-for="HasUniqueFeature" value="@YesNoOptions.No" onclick="clearInput()">
                                <label class="govuk-label govuk-radios__label" for="HasUniqueFeatureNo">
                                    @sharedlocalizer["No"]
                                </label>
                            </div>

                        </div>
                    </div>
                </fieldset>
            </div>


            <div class="govuk-button-group">
                <button class="govuk-button" data-module="govuk-button" type="submit">
                    @sharedlocalizer["Continue"]
                </button>
            </div>
        }

    </div>
</div>

@section Scripts
    {

    <script>
        function clearInput() {
            document.getElementById("FeatureDescription").value = "";
        }
    </script>
}

src/Defra.PTS.Web.UI/Views/TravelDocument/PetGender.cshtml
@model PetGenderViewModel
@using Defra.PTS.Web.Domain.ViewModels.TravelDocument;
@using Defra.PTS.Web.Domain.Enums;
@using Defra.PTS.Web.Domain.ViewModels;
@using Defra.PTS.Web.UI.Constants;
@using Defra.PTS.Web.UI.Extensions;
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer
@using Microsoft.Extensions.Localization;
@inject IStringLocalizer<ISharedResource> sharedlocalizer

@{
    var fieldsetLegend = new FieldsetLegendViewModel { Label = @Localizer["What sex is your pet?"].Value, LabelFor = "Female" };
    this.SetMetaTitle(@Localizer["What sex is your pet?"].Value);
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">

        @using (Html.BeginForm("PetGender", "TravelDocument", FormMethod.Post, new { @class = "form PetGender" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.IsCompleted)

            <partial name="_ErrorSummary" />

            <div id="formroot" class="govuk-form-group @(ViewData.ModelState.IsValid ? "" : "govuk-form-group--error")">

                <fieldset class="govuk-fieldset">

                    <partial name="_FieldsetLegend" model=fieldsetLegend />

                    @Html.ValidationMessageFor(x => x.Gender, string.Empty, new { @class = "govuk-error-message" })

                    <div class="govuk-form-group" id="Gender">
                        <div class="govuk-radios" data-module="govuk-radios">
                            <div class="govuk-radios__item">
                                @Html.RadioButtonFor(m => m.Gender, PetGender.Female, new { @class = "govuk-radios__input", id = "Female", data_aria_controls = "conditional-MicrochipNumber" })
                                <label class="govuk-label govuk-radios__label" for="Female">
                                    @Localizer["Female"]
                                </label>
                            </div>
                            <div class="govuk-radios__item">
                                @Html.RadioButtonFor(m => m.Gender, PetGender.Male, new { @class = "govuk-radios__input", id = "Male", data_aria_controls = "conditional-MicrochipNumber" })
                                <label class="govuk-label govuk-radios__label" for="Male">
                                    @Localizer["Male"]
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>

            <div class="govuk-form-group">
                <button class="govuk-button" data-module="govuk-button" type="submit">
                    @sharedlocalizer["Continue"]
                </button>
            </div>
        }

    </div>
</div>

src/Defra.PTS.Web.UI/Views/TravelDocument/PetKeeperAddressManual.cshtml
@model PetKeeperAddressManualViewModel
@using Defra.PTS.Web.Application.Extensions
@using Defra.PTS.Web.Domain.ViewModels.TravelDocument;
@using Defra.PTS.Web.Domain.Enums;
@using System.Web;
@using Defra.PTS.Web.Domain.ViewModels;
@using Defra.PTS.Web.UI.Constants;
@using Defra.PTS.Web.UI.Extensions;
@using Defra.PTS.Web.Application.Constants;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@using Microsoft.Extensions.Localization;
@inject IStringLocalizer<ISharedResource> sharedlocalizer

@{
    var fieldsetLegend = new FieldsetLegendViewModel { Label = (Localizer[PetKeeperAddressManualViewModel.FormTitle].Value), LabelFor = "AddressLineOne" };
    this.SetMetaTitle(Localizer[PetKeeperAddressManualViewModel.FormTitle].Value);
    var errorOrder = new string[] { "AddressLineOne", "AddressLineTwo", "TownOrCity", "County", "Postcode" };
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        @using (Html.BeginForm("PetKeeperAddressManual", "TravelDocument", FormMethod.Post, new { @class = "form PetKeeperAddressManual" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.IsCompleted)
            @Html.HiddenFor(x => x.PostcodeRegion)

            <partial name="_ErrorSummaryOrdered" model=errorOrder />

            <div class="govuk-form-group">
                <fieldset class="govuk-fieldset">
                    <partial name="_FieldsetLegend" model=fieldsetLegend />

                    <div id="address-hint" class="govuk-hint">
                        @Localizer["Enter a valid address in England, Scotland or Wales."]
                    </div>

                    <div class="govuk-form-group @(ViewData.ModelState.HasError("AddressLineOne") ? "govuk-form-group--error" : null)">
                        <div class="govuk-label" for="AddressLineOne">
                            @Localizer["Address line 1"]
                        </div>
                        @Html.ValidationMessageFor(x => x.AddressLineOne, string.Empty, new { @class = "govuk-error-message" })
                        @Html.TextBoxFor(x => x.AddressLineOne, new { @class = "govuk-input", @spellcheck = "false", @autocomplete = @WebAppConstants.FormAutofill.AddressLineOne, aria_label = "Address line 1" })
                    </div>

                    <div class="govuk-form-group">
                        <div class="govuk-label" for="AddressLineTwo">
                            @Localizer["Address line 2 (optional)"]
                        </div>
                        @Html.ValidationMessageFor(x => x.AddressLineTwo, string.Empty, new { @class = "govuk-error-message" })
                        @Html.TextBoxFor(x => x.AddressLineTwo, new { @class = "govuk-input", @spellcheck = "false", @autocomplete = @WebAppConstants.FormAutofill.AddressLineTwo, aria_label = "Address line 2 (optional)" })
                    </div>

                    <div class="govuk-form-group @(ViewData.ModelState.HasError("TownOrCity") ? "govuk-form-group--error" : null)">
                        <div class="govuk-label" for="TownOrCity">
                            @Localizer["Town or city"]
                        </div>
                        @Html.ValidationMessageFor(x => x.TownOrCity, string.Empty, new { @class = "govuk-error-message" })
                        @Html.TextBoxFor(x => x.TownOrCity, new { @class = "govuk-input govuk-!-width-two-thirds", @spellcheck = "false", @autocomplete = @WebAppConstants.FormAutofill.CityOrTown, aria_label = "Town or city" })
                    </div>

                    <div class="govuk-form-group">
                        <div class="govuk-label" for="County">
                            @Localizer["County (optional)"]
                        </div>
                        @Html.ValidationMessageFor(x => x.County, string.Empty, new { @class = "govuk-error-message" })
                        @Html.TextBoxFor(x => x.County, new { @class = "govuk-input govuk-!-width-two-thirds", @spellcheck = "false", aria_label = "County (optional)" })
                    </div>

                    <div class="govuk-form-group @(ViewData.ModelState.HasError("Postcode") ? "govuk-form-group--error" : null)">
                        <div class="govuk-label" for="Postcode">
                            @Localizer["Postcode"]
                        </div>
                        @Html.ValidationMessageFor(x => x.Postcode, string.Empty, new { @class = "govuk-error-message" })
                        @Html.TextBoxFor(x => x.Postcode, new { @class = "govuk-input govuk-input--width-10", @spellcheck = "false", aria_label = "Postcode" })
                    </div>
                </fieldset>
            </div>

            <div class="govuk-button-group">
                <button class="govuk-button" data-module="govuk-button" type="submit">
                    @sharedlocalizer["Continue"]
                </button>
            </div>
        }
    </div>
</div>

src/Defra.PTS.Web.UI/Views/TravelDocument/PetKeeperNonGbAddress.cshtml
@model PetKeeperUserDetailsViewModel

@using Defra.PTS.Web.Domain.ViewModels.TravelDocument;
@using Defra.PTS.Web.Domain.Enums;
@using Defra.PTS.Web.Domain.ViewModels;
@using Defra.PTS.Web.UI.Constants;
@using Defra.PTS.Web.UI.Extensions;
@using Microsoft.Extensions.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer localizer
@inject IStringLocalizer<ISharedResource> sharedlocalizer

@{
    var fieldsetLegend = new FieldsetLegendViewModel { Label = localizer[PetKeeperUserDetailsViewModel.PetKeeperNonGbAddressFormTitle].Value, LabelFor = "Yes" };
    this.SetMetaTitle(localizer[PetKeeperUserDetailsViewModel.PetKeeperNonGbAddressFormTitle].Value);
}

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">


        @using (Html.BeginForm("PetKeeperNonGbAddress", "TravelDocument", FormMethod.Post, new { @class = "form PetKeeperNonGbAddress" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.IsCompleted)
            @Html.HiddenFor(x => x.Name)
            @Html.HiddenFor(x => x.Email)
            @Html.HiddenFor(x => x.Phone)
            @Html.HiddenFor(x => x.AddressLineOne)
            @Html.HiddenFor(x => x.TownOrCity)
            @Html.HiddenFor(x => x.County)
            @Html.HiddenFor(x => x.Postcode)
            @Html.HiddenFor(x => x.PostcodeRegion)

            <div class="govuk-form-group">

                <fieldset class="govuk-fieldset">

                    <partial name="_FieldsetLegend" model=fieldsetLegend />
                    <section class="govuk-notification-banner govuk-!-static-margin-top-6"
                         aria-labelledby="govuk-notification-banner-title"
                         data-module="govuk-notification-banner">
                        <div class="govuk-notification-banner__header">
                            <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                                @localizer[@PetKeeperUserDetailsViewModel.PetKeeperNonGbAddressFormMessageHeader]
                            </h2>
                        </div>
                        <div class="govuk-notification-banner__content">
                            <p class="govuk-notification-banner__heading">
                                @localizer[@PetKeeperUserDetailsViewModel.PetKeeperNonGbAddressFormMessageBody]
                            </p>
                        </div>
                    </section>
                    <dl class="govuk-summary-list">
                        <div class="govuk-summary-list__row">
                            <dt class="govuk-summary-list__key">@sharedlocalizer["Name"]</dt>
                            <dd class="govuk-summary-list__value">@Model.Name</dd>

                        </div>
                        <div class="govuk-summary-list__row">
                            <dt class="govuk-summary-list__key">@sharedlocalizer["Email"]</dt>
                            <dd class="govuk-summary-list__value">@Model.Email</dd>

                        </div>
                        <div class="govuk-summary-list__row">
                            <dt class="govuk-summary-list__key">
                                @sharedlocalizer["Address"]
                            </dt>
                            <dd class="govuk-summary-list__value">
                                @Model.AddressLineOne<br />
                                @Model.TownOrCity<br />
                                @if (!string.IsNullOrWhiteSpace(Model.County))
                                {
                                    @Model.County<br />
                                }
                                @Model.Postcode
                            </dd>

                        </div>
                        <div class="govuk-summary-list__row">
                            <dt class="govuk-summary-list__key">@sharedlocalizer["Phone number"]</dt>
                            <dd class="govuk-summary-list__value">@Model.Phone</dd>

                        </div>
                    </dl>

                </fieldset>
            </div>

            <div class="govuk-form-group">
                <button class="govuk-button" data-module="govuk-button" type="submit">
                    @sharedlocalizer["Continue"]
                </button>
            </div>
        }

    </div>
</div>